language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ngtailor' ]; then cd .. && eval "mv $currentfolder generator-ngtailor" && cd generator-ngtailor; fi

